# basic options
title: There Is No Box
author: tapherjspiteri
email: 
description: Blog Coming Soon
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
