# basic options
title: There Is No Box
author: tapherjspiteri
email: inthetechroom@gmail.com
description: Blog Coming Soon
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
